[project]
name = "record-replay"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "keyboard>=0.13.5",
    "pyautogui>=0.9.54",
    "pynput>=1.8.1",
]
